### ISSUE TITLE
Question about phone random macs

### ISSUE THREAD

**Issue by btsimonh** [h2zero/NimBLE-Arduino#193]
Hi H2zero/all,

one question that comes up a lot in Tasmota is 'why can't I see my device'.
This is because by default I ignore all macs which are not type 0 (public) addresses.
The reason is that phones advertise with 'Static random' type 1, changing the address every few mins.
We have a config to enable the 'max' address type; but then people complain about being swamped with useless adverts :(.

But, other devices use type 1 and keep their macs much longer, and these are useful to hear....

Does anyone have some insights on how to ignore the phone random addresses, but receive the other devices?  I guess we could have a list of service data types to trigger packet discard, but maybe someone has a better scheme?

br,

Simon 

p.s. We've adopted NimBLE 1.2.0 - it will be in the release Tasmota (hopefully released today all things well).... thankyou again.
Do we expect anything better from arduino Rc7? (not in the TAS release yet).

**Comment by h2zero** [comment]
Hi @btsimonh I cannot suggest much in the way of filtering other than possibly ignoring iOS advertisements by checking for manufacturer data starting with 4c00. However, if that data is needed the only other thing to reduce the traffic is to use the duplicate filter settings so they are only reported once (up to a limit).

rc7 doesn't change much for BLE, if anything, than rc5-6 did. Controller timeout crashes are likely depending on usage. I'm hopeful something gets fixed in that regard soon.
