### ISSUE TITLE
Low level connect for NimBLEClient

### ISSUE THREAD

**Issue by DTTerastar** [h2zero/NimBLE-Arduino#299]
My project https://github.com/ESPresense/ESPresense is trying to connect to quite a few different devices quickly and get the model number and/or name.  It sort of works but since connect doesn't return an error code I can't do retries based on the error codes.  Is there a way to make a lower level connect that allows you to get the codes?  Connect is also blocking so you can't easily do simultaneous connections.  Any other suggestions on how to make the connections more reliable would be helpful: https://github.com/ESPresense/ESPresense/blob/ab7e387c22030f80f07330912d3e9105d05e0356/lib/BleFingerprint/BleFingerprint.cpp#L303

ATM even after 10 attempts i'm only like 80% successful.  (iPhones rotate the mac every 15 minutes so it needs to work every 15 minutes)

**Comment by DTTerastar** [comment]
Oh and it'd be nice to be able to avoid the logging to the console for this call:

```lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
E NimBLEClient: "Connection failed; status=574 "
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
E NimBLEClient: "Connection failed; status=574 "
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
E NimBLEClient: "Connection failed; status=574 "
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
E NimBLEClient: "Connection failed; status=574 "
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
E NimBLEClient: "Connection failed; status=574 "
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
E NimBLEClient: "Connection failed; status=574 "```

**Comment by corgan2222** [comment]
It would be great to have a solution for this Problem. 

![grafik](https://user-images.githubusercontent.com/12233951/136083336-2e557758-34d9-4569-b1b6-d1529b030342.png)

**Comment by h2zero** [comment]
BLE connections will only occur when the server device is listening for them. This is usually only for short periods of time after advertising intervals. If you're cycling through connections to a large number of devices it's likely some of them have stopped listening by the time you attempt connection.

NimBLE supports multiple connections but can only be actively trying to connect to 1 device at a time, that's why the call blocks.

If you want to experiment with the low level NimBLE calls you can look in NimBLEClient.cpp and look for ble_gap_connect within NimBLE itself. I'd be curious of any ideas you come up with.

The ll_pdu messages come from the espressif controller and we have no way to disable them. Only solution is to update the arduino core / IDF version to a version after espressif removed that. The NimBLE error can just be commented out if you don't want to see it.

**Comment by h2zero** [comment]
Ok, I see. A get last error function added to the client?

**Comment by DTTerastar** [comment]
Yeah, that'll work

**Comment by DTTerastar** [comment]
I still find having callbacks in a blocking function very weird, but I know you're trying to be compatible with an older api.

**Comment by h2zero** [comment]
Yes, it's not really necessary for this but it doesn't hurt much. It wasn't an easy job to put this together in the same API but it worked out 😃.

I'll be busy tonight but I'll look to add the function when I have a few minutes.

**Comment by h2zero** [comment]
I can see you've already done what you need but let me know if #300 works for you.
