### ISSUE TITLE
GATT_INSUF_RESOURCE when trying to write data to characteristic

### ISSUE THREAD

**Issue by qdlmcfresh** [h2zero/NimBLE-Arduino#377]
Im trying to send about 300 to 400 bytes to a characteristic but get error GATT_INSUF_RESOURCE (0x11). Reading the same amount of data from the same characteristic works though

**Comment by h2zero** [comment]
That's a return code from the peer device usually. What is the device you're sending the bytes to?

**Comment by qdlmcfresh** [comment]
Im sending from an android phone to an esp32

**Comment by h2zero** [comment]
Oh okay, in that case would it be possible to provide a log from the esp32 when this occurs? My initial thought is this is most likely being sent as a long write, which could cause this due to limited buffers. You could try increasing [this value](https://github.com/h2zero/NimBLE-Arduino/blob/c0d1ce06fc34de72f88cdfdd4ef577d0e783a40c/src/nimconfig.h#L83)

**Comment by qdlmcfresh** [comment]
Your first thought seems to be right. increasing CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT works. Thank you :)
