### ISSUE TITLE
Error While Compiling for adafruit_feather_nrf52832

### ISSUE THREAD

**Issue by muhdRiz07** [h2zero/NimBLE-Arduino#448]
I modified the platform.ini file as per the instruction given in readme.md file but giving error 'board_bootloader to be specified'.(refer screenshot 1 & 2)
when i add board_bootloader = adafruit it's giving library error(screen shot 3 & 4)
![Screenshot1](https://user-images.githubusercontent.com/113683393/190619451-ac7d1e1a-7a0e-4a0a-9e72-6c1ccad64679.png)
![Screenshot2](https://user-images.githubusercontent.com/113683393/190619461-a097b254-f240-4435-afbf-4e8a6e8475bd.png)
![Screenshot3](https://user-images.githubusercontent.com/113683393/190619463-1a297a59-f982-4405-9047-1659c27a13e4.png)
![Screenshot4](https://user-images.githubusercontent.com/113683393/190619468-dcb154e7-69a7-41ea-9ec9-9c226638b524.png)
**board:adafruit_feather_nrf52832
   ide: platformio**

**Comment by h2zero** [comment]
Hi @muhdRiz07, the problem here is cause by the line `board_build.mcu = nrf52832`. You do not need to specify this as it's defined in the board by the platform. However, if you want to define it the correct way is `board_build.mcu = nrf52832_xxaa`, the reason is this value is used to set a compile flag.

Note that adafruit boards require specifying the bootloader to use, if you're not using one you should set `board_bootloader = none`

**Comment by muhdRiz07** [comment]
Hi @h2zero, now it's working,**Thanks** for the support.
