### ISSUE TITLE
Any way to manipulate adv payload on byte/word basis?

### ISSUE THREAD

**Issue by kbhuinfo** [h2zero/NimBLE-Arduino#490]
There is a way to `setAdvertisementData` in the advertising, but getting a pointer to it does not. How do I read the string or char* and then modify the bits/bytes/words in it? (my real problem is, that the only way to do that is to completely overwrite the adv data, which is not my goal)

**Comment by h2zero** [comment]
I think what you need is `NimBLEAdvertisementData::getPayload`, assuming you are setting the data with `NimBLEAdvertising::setAdvertisementData` you could manipulate the data in the std::string returned then call `NimBLEAdvertisementData::addData(std::string)`. Otherwise there is no direct manipulation API.
